name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp_zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          sudo apt-get install -y nodejs npm

      - name: Download and Extract OWASP ZAP
        run: |
          wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar -xzf ZAP_2.11.0_Linux.tar.gz

      - name: Install Juice Shop Dependencies and Run Tests
        run: |
          cd juice-shop
          npm install
          npm run test:server
          npm run test:e2e

      - name: Copy Code Coverage Files
        run: |
          cp juice-shop/build/reports/coverage/server-tests/lcov.info server-lcov.info
          cp juice-shop/build/reports/coverage/e2e-tests/lcov.info e2e-lcov.info

      - name: Run OWASP ZAP Scan
        run: |
          cd ../ZAP_2.11.0
          ./zap.sh -cmd -quickurl https://juice-shop.herokuapp.com -quickprogress -quickout /zap/report.html

      - name: Upload Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: /zap/report.html
